### ISSUE TITLE
Threshold  & accuracy

### ISSUE THREAD

**Issue by m3m3-chan** [stepacool/Eye-Tracker#7]
Hello, 
Thanks for the great project.
I ran the noGUI ver on my Windows machine & I noticed the detection doesn't pickup unless I raise the threshold to 70 or so.. does that affect the accuracy of the detection alot? Is there a recommended threshold or an ideal setting to give better accuracy?
Also, can I use the code to detect more than 1 face?

thanks,

**Comment by stepacool** [comment]
Hello, glad to see your appreciation.

Threshold is about how dark your video is. If it's dark, set a low threshold(around 40), if it's really bright, set a high threshold(around 150). 

And of course you can use it for more than once face, but since the process is quite demanding in terms of computational resource, you probably will need multiprocessing(not certain about this).

Regards.

**Comment by m3m3-chan** [comment]
@stepacool Thanks for response! 
I will try your suggestion and update if I get good results.
